<?php

namespace Medicina\BackendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OficinaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OficinaRepository extends EntityRepository
{
}