# Rutas importadas del bundle BackendBundle
BackendBundle:
    resource: "@BackendBundle/Resources/config/routing.yml"
    prefix:   /backend
    
TallerKernelKernelBundle:
    resource: "@TallerKernelKernelBundle/Resources/config/routing.yml"
    prefix:   /
