parameters:
#    taller_kernel_kernel.example.class: Taller\Kernel\KernelBundle\Example

services:
#    taller_kernel_kernel.example:
#        class: %taller_kernel_kernel.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
