catedra:
    pattern:  /
    defaults: { _controller: "BackendBundle:Catedra:index" }

catedra_show:
    pattern:  /{id}/show
    defaults: { _controller: "BackendBundle:Catedra:show" }

catedra_new:
    pattern:  /new
    defaults: { _controller: "BackendBundle:Catedra:new" }

catedra_create:
    pattern:  /create
    defaults: { _controller: "BackendBundle:Catedra:create" }
    requirements: { _method: post }

catedra_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "BackendBundle:Catedra:edit" }

catedra_update:
    pattern:  /{id}/update
    defaults: { _controller: "BackendBundle:Catedra:update" }
    requirements: { _method: post }

catedra_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "BackendBundle:Catedra:delete" }
    requirements: { _method: post }
