oficina:
    pattern:  /
    defaults: { _controller: "BackendBundle:Oficina:index" }

oficina_show:
    pattern:  /{id}/show
    defaults: { _controller: "BackendBundle:Oficina:show" }

oficina_new:
    pattern:  /new
    defaults: { _controller: "BackendBundle:Oficina:new" }

oficina_create:
    pattern:  /create
    defaults: { _controller: "BackendBundle:Oficina:create" }
    requirements: { _method: post }

oficina_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "BackendBundle:Oficina:edit" }

oficina_update:
    pattern:  /{id}/update
    defaults: { _controller: "BackendBundle:Oficina:update" }
    requirements: { _method: post }

oficina_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "BackendBundle:Oficina:delete" }
    requirements: { _method: post }
